---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/yaml-schema.json
name: "ctat"
description: write your description here
keywords:
  - mutation
  - GATK4
  - genomics
tools:
  - "ctat":
      description: "Variant calling pipeline focussed on detecting variants from RNA sequencing (RNA-seq) data"
      homepage: "https://github.com/NCIP/ctat-mutations"
      documentation: "https://github.com/NCIP/ctat-mutations/wiki"
      tool_dev_url: "https://github.com/NCIP/ctat-mutations"
      licence: "The Broad Institute"

input:
   # Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]

#  - sample_id:
#      type: string
#      description: The sample id
#      pattern: "*"

  - outputdir:
      type: string
      description: Name to be given to the directory in which CTAT-Mutation outputs will be placed.
      pattern: "*"

  - left:
      type: file
      description: Path to the location of the left (ie. /1) paired end RNA-Seq Fastq file.
      pattern: "*.fastq.gz"

  - right:
      type: file
      description: Path to the location of the right (ie, /2) paired end RNA-Seq Fastq file.
      pattern: "*.fastq.gz"

output:
  #Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test']

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

  - initial_variants:
      type: file
      description: The initially predicted variants
      pattern: "*.vcf"

  - hard_cutoffs_variants:
      type: file
      description: Variants after applying hard cutoffs to remove likely false positives
      pattern: "*.vcf"

  - cancer_variants:
      type: file
      description: The subset of variants that are considered most relevant to cancer biology
      pattern: "*.vcf"

  - html:
      type: file
      description: Self-contained web-application for interactively navigating the cancer variants
      pattern: "*.html"

authors:
  - "@NadineKraft"
